### ISSUE TITLE
[Feature] adding `options` class method

### ISSUE THREAD

**Issue by rudyyazdi** [dry-rb/dry-initializer#10]
Hey guys,

Great Job on this one, a quick suggestion, do you think this pattern is a good idea:

```ruby
class User
  extend Dry::Initializer::Mixin

  options :admin, :phone, :email, :address

  # the rest ...
end
```

If yes, let me know and I'll submit a PR ;)

Cheers,

**Comment by nepalez** [comment]
Ouch! Sorry @rudyyazdi, I've somehow missed your issue

I'm not sure about this kind of DSL, finding it too strict. The method you've suggested builds several options, that are (1) all required (because they have neither `default`, nor `optional` keys); (2) has no type constraint.

I think using `dry-initializer` for this kind of staff is an overkill. Maybe for cases when you need a structure without type control you should use other solutions like `Hashie::Mash`
