### ISSUE TITLE
`#using` method breaks Ruby refinements

### ISSUE THREAD

**Issue by sahal2080** [dry-rb/dry-initializer#16]
With refinements in my code I keep getting 
```
Uncaught exception: wrong number of arguments (given 1, expected 0)
```

**Comment by nepalez** [comment]
D'oh! Thank you, you're right.
I'd say this is because refinements are not much popular in dry community ;)

Well, technically we could rename `using` to `with` or `with_settings` in `v0.10.0`. This would break backward compatibility, but... well, this feature was not stabilized, so it is acceptable for me.

@jmgarnier @hrom512 I hope this would not affect you too hard?

**Comment by hrom512** [comment]
@nepalez I fixed it in https://github.com/dry-rb/dry-initializer/pull/17

**Comment by jmgarnier** [comment]
Thanks @nepalez No I am fine;)
