### ISSUE TITLE
Overriding options not working in inherited class

### ISSUE THREAD

**Issue by vdhpieter** [dry-rb/dry-initializer#35]
I'm going to explain it with an example:
```ruby
class Product
  extend ::Dry::Initializer

  option :name
end

class Book < Product
  option :data
  option :name, default: proc { data[:name] }
end
```
When I used these classes in the console this happend:
```
irb(main):001:0> Product.new(name: "haha")
#<Product:0x00007fc3418ab400 @__options__={:name=>"haha"}, @name="haha">
irb(main):002:0> Book.new(data: {name: "haha"})
NoMethodError: undefined method `[]' for nil:NilClass
	from /Users/pieter/Repos/main-app/app/lib/book.rb:3:in `block in <class:Book>'
	from (eval):4:in `instance_exec'
	from (eval):4:in `block in __initialize__'
	from (eval):4:in `fetch'
	from (eval):4:in `__initialize__'
	from /Users/pieter/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/dry-initializer-1.4.1/lib/dry/initializer/instance_dsl.rb:8:in `initialize'
	from (irb):8:in `new'
	from (irb):8
	from /Users/pieter/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.0.2/lib/rails/commands/console.rb:65:in `start'
	from /Users/pieter/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.0.2/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/pieter/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/pieter/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/pieter/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```
Reading your docs I thought I could override options in subclasses:
http://dry-rb.org/gems/dry-initializer/inheritance/
And I can refer to other arguments in defaults:
http://dry-rb.org/gems/dry-initializer/optionals-and-defaults/

So what am I doing wrong? Is their something I missed?

**Comment by nepalez** [comment]
Hi @vdhpieter 

The problem here is the following. When an option is reloaded in a subclass, this means that only "local" definition is changed, but not the order. This is done by  intention -- because (as you'll see later) the order matters.

This why option `:name` still goes first, and the whole sequence of definitions you've made are equal to this one:

```ruby
class Book
  extend Dry::Initializer

  option :name, default: proc { data[:name] }
  option :data
end
```

The problem with this code is that `@name` is initialized before the `@data` (btw you could check the generated code of the initializer via `Book.dry_initializer.code`); at this moment `@data` is not initialized yet.

I mentioned this behavior is intentional; This is because a superclass could use defaults by itself, and changing the order of initialization could break that assignments.

**Comment by vdhpieter** [comment]
Ok that makes sense, thx for the explanation. I already found another way to get my intended behaviour :-)
