### ISSUE TITLE
Multiple params|options with same definition at one line

### ISSUE THREAD

**Issue by belousovAV** [dry-rb/dry-initializer#43]
```
class MyClass
  include Dry::Initializer.define -> do
    param :a, proc(&:to_i)
    param :b, proc(&:to_i)
    param :c, proc(&:to_i)
    param :d, proc(&:to_i)
  end
end
```
DRY?

**Comment by nepalez** [comment]
Could you please describe the problem with a bit more details?
I see no problems with your snippet

**Comment by belousovAV** [comment]
Sorry.
I mean `param [:a, :b, :c, :d], proc(&:to_i)`, instead of `[:a, :b, :c, :d].each { |name|  param name, proc(&:to_i) }`

**Comment by nepalez** [comment]
I'd prefer not to add this behaviour because it leads to worse readability.

Actually, the syntax of dry-initializer was inspired by the `inch` gem. Concerning verbosity the real difference is between:

```ruby
param :foo, method(:String)
param :bar, method(:String)
```

and

```ruby
# param [String] foo
# param [String] bar
def initialize(foo, bar)
  @foo, @bar = foo, bar
end
```

With `param [:a, :b, :c, :d]` this readability would be lost.

If you're ok with writing something like `[:a, :b, :c, :d].each { |name| param name, proc(&:to_i) }`, I think you should't use `dry-initializer` at all (remember that the gem by itself adds some overhead). You'd better use PORO initializer -- at least, readers of your code will see the code they accustomed to.
