### ISSUE TITLE
Work out semver-appropriate way to release now-yanked 2.6.0 changes [was: "2.6.0 broke public API"]

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-initializer#47]
Unfortunately, [this](https://github.com/dry-rb/dry-initializer/commit/128b484c5e0243890214b7e90fc97607b8493466) broke public behavior that rom relies on, hence [this issue](https://github.com/rom-rb/rom/issues/503) was reported.

Please yank 2.6.0 and release it again as 3.0.0.

**Comment by timriley** [comment]
As mentioned in 
https://github.com/rom-rb/rom/issues/503#issuecomment-423478433, I've yanked 2.6.0 (thanks @nepalez for helping us gain access to the ruby gems entry while on vacation!).

I haven't made any new release since I think our approach for this would be best decided once @nepalez is back in a week or so.

Am updating the name of this issue to remind us to work out how to make this next release.
