### ISSUE TITLE
[Feature Request] Option to skip type checking in certain cases

### ISSUE THREAD

**Issue by CodingAnarchy** [dry-rb/dry-initializer#66]
We have a number of tests that will pass in `object_double([class])` when we are running specs for our Rails application, but these all fail on the `Types.Instance([class])` checks we are  using.  As it is difficult to add an option for a test double, since these classes are not even loaded in production environments, there is not an easy way to skip these type checks when needed.

It would be great if we could pass in an extra option to ignore the type checking in certain scenarios.  Something like `option :arg, type: Types.Instance(Foo), ignore_type: Rails.env.test?` would be ideal.

**Comment by CodingAnarchy** [comment]
The only way I was able to get this working for our system at present is to construct something like this:

```
type_check = Rails.env.test? Types.Instance(Object) : Types.Instance(Foo)
option :arg, type: type_check
```

Which, while functional, is not really ideal.

**Comment by nepalez** [comment]
@CodingAnarchy Hi!

I don't think we should add this settings directly into dry-initializer just because this seems like an edge case on far edge. This is a "bad news"

But there's a good news too :)
Option definition is actually extensible via dispatchers. This means you can insert your own setting to `option` and `param`.

I would recommend you to read the [dispatchers class](https://github.com/dry-rb/dry-initializer/blob/master/lib/dry/initializer/dispatchers.rb) with its sublcasses to look at how exactly they are implemented. Then you should possibly read [dry-initializer-rails](https://github.com/nepalez/dry-initializer-rails/blob/master/lib/dry/initializer/rails.rb) as an example of adding new setting.

**Comment by nepalez** [comment]
I think you need a dispatcher like this:

```ruby
# Define a dispatcher
dispatcher = lambda do |ignore_type: nil, **options|
  ignore_type&.call ? options.reject { |k| k == :type } : options
end

# Then register a dispatcher
Dry::Initializer::Dispatchers << dispatcher
```

You can either do this in your application or define a gem extending `dry-initalizer` just like `dry-initialize-rails` does
