### ISSUE TITLE
Ruby 3 support

### ISSUE THREAD

**Issue by olkeene** [dry-rb/dry-initializer#96]
## Describe the bug

Hey guys,
We're using DRY-ecosystem and extremely enjoying its flexibility.
During migration to ruby 3, was found that `dry-initializer` produces the below warning which blocks the migration

```
dry-initializer-3.1.1/lib/dry/initializer/mixin/root.rb:11: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
(eval):2: warning: The called method `__dry_initializer_initialize__' is defined here
```

## To Reproduce

Provide detailed steps to reproduce, **an executable script would be best**.
```
RUBYOPT='-W:deprecated' DEPRECATION_BEHAVIOR="record" bundle exec YourTestCMD
```

## My environment

- Affects my production application: **YES**
- Ruby version: 2.7
- OS: linux

**Comment by flash-gordon** [comment]
It is very likely the problem is caused by your code and not by dry-initializer. Check the code where dry-initializer gets called, likely you don't pass values as keywords. If the problem persists, ask a question with failing code at [our forum](https://discourse.dry-rb.org/), and we'll sort you out.
